include("dependencies.jl")
include("sim.jl")
include("exp.jl")
include("exp_1D.jl")

const n_meas_start = parse(Int64,ARGS[1])
const n_meas_end = parse(Int64,ARGS[2])
const n_meas_step = parse(Int64,ARGS[3])
const depth_start = parse(Int64,ARGS[4])
const depth_end = parse(Int64,ARGS[5])
const depth_step = parse(Int64,ARGS[6])
const n_Asites = parse(Int64,ARGS[7])
const n_Bsites = parse(Int64,ARGS[8])
const n_Csites = parse(Int64,ARGS[9])
const nsim = parse(Int64,ARGS[10])
const file_name = ARGS[11]

n_meas_l = floor.(Int,collect(range(n_meas_start,stop=n_meas_end,step=n_meas_step)))
n_meas_length = length(n_meas_l)
depth_l = floor.(Int,collect(range(depth_start,stop=depth_end,step=depth_step)))
depth_length = length(n_meas_l)
SAB_ave_arr,SAB_std_arr,SBC_ave_arr,SBC_std_arr,SB_ave_arr,SB_std_arr,SABC_ave_arr,SABC_std_arr = scanNerasDepth1D(simBWEras1D,n_Asites,n_Bsites,n_Csites,n_meas_start,n_meas_end,n_meas_step,depth_start,depth_end,depth_step,nsim,true)
save2DData(n_meas_l,depth_l,SAB_ave_arr,SAB_std_arr,string(file_name,"_SAB"))
save2DData(n_meas_l,depth_l,SBC_ave_arr,SBC_std_arr,string(file_name,"_SBC"))
save2DData(n_meas_l,depth_l,SB_ave_arr,SB_std_arr,string(file_name,"_SB"))
save2DData(n_meas_l,depth_l,SABC_ave_arr,SABC_std_arr,string(file_name,"_SABC"))
